
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */

pragma ton-solidity >=0.35.0;
pragma AbiHeader expire;
pragma AbiHeader time;
pragma AbiHeader pubkey;
import "AbstractDebotListInit.sol";

// This is class that describes you smart contract.
contract FillingShoppingList is AbstractDebotListInit {

    string purchaseName;
    
    function _menu() internal override{
        string sep = '----------------------------------------';
        Menu.select(
            format(
                "You have {}/{} (unpaid/paid) purchases for {} total sum",
                    m_summary.unpaidCount,
                    m_summary.paidCount,
                    m_summary.sum
            ),
            sep,
            [
                MenuItem("Add new purchase","",tvm.functionId(addPurchaseName)),
                MenuItem("Show purchase list","",tvm.functionId(showPurchase)),
                 MenuItem("Delete task","",tvm.functionId(deletePurchase))
            ]
        );
    }

    function addPurchaseName(uint32 index) public {
        index = index;
        Terminal.input(tvm.functionId(addPurchaseNumber), "One line please:", false);
    }

    function addPurchaseNumber(string name) public {
        purchaseName = name;
        Terminal.input(tvm.functionId(addPurchase_), "One line please:", false);
    }

    function addPurchase_(string number) public view {
        (uint256 purchaseNum,)= stoi(number);
        uint32 purchaseNumber = uint32(purchaseNum);
        optional(uint256) pubkey = 0;
        ShoppingListInterface(m_address).addPurchase{
                abiVer: 2,
                extMsg: true,
                sign: true,
                pubkey: pubkey,
                time: uint64(now),
                expire: 0,
                callbackId: tvm.functionId(onSuccess),
                onErrorId: tvm.functionId(onError)
            }(purchaseName, purchaseNumber);
    }

    function showPurchase(uint32 index) public view {
        index = index;
        optional(uint256) none;
        ShoppingListInterface(m_address).getPurchase{
            abiVer: 2,
            extMsg: true,
            sign: false,
            pubkey: none,
            time: uint64(now),
            expire: 0,
            callbackId: tvm.functionId(showPurchase_),
            onErrorId: 0
        }();
    }

    function showPurchase_( Purchase [] purchaseArray ) public {
        uint32 i;
        if (purchaseArray.length > 0 ) {
            Terminal.print(0, "Your purchase list:");
            for (i = 0; i < purchaseArray.length; i++) {
                Purchase purchase = purchaseArray[i];
                string bought;
                if (purchase.isBought) {
                    bought = '✓';
                } else {
                    bought = ' ';
                }
                Terminal.print(0, format("{} {}  {}{}  at {}", purchase.id, bought, purchase.number, purchase.name, purchase.createdAt));
            }
        } else {
            Terminal.print(0, "Your purchase list is empty");
        }
        _menu();
    }

    function deletePurchase(uint32 index) public {
        index = index;
        if (m_summary.paidCount + m_summary.unpaidCount > 0) {
            Terminal.input(tvm.functionId(deletePurchase_), "Enter purchase number:", false);
        } else {
            Terminal.print(0, "Sorry, you have no purchases to delete");
            _menu();
        }
    }

    function deletePurchase_(string value) public view {
        (uint256 num,) = stoi(value);
        optional(uint256) pubkey = 0;
        ShoppingListInterface(m_address).deletePurchase{
                abiVer: 2,
                extMsg: true,
                sign: true,
                pubkey: pubkey,
                time: uint64(now),
                expire: 0,
                callbackId: tvm.functionId(onSuccess),
                onErrorId: tvm.functionId(onError)
            }(uint32(num));
    }

    function setStat(SummaryOfShopping summary) public override {
        m_summary = summary;
        _menu();
    }
   

}
