
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */

pragma ton-solidity >=0.35.0;
pragma AbiHeader expire;
pragma AbiHeader time;
pragma AbiHeader pubkey;
import "ShoppingListStructures.sol";

// This is class that describes you smart contract.
interface ShoppingListInterface {
   function getStat() external returns (SummaryOfShopping summary);
   function addPurchase (string name, uint32 number) external;
   function deletePurchase (uint32 id) external;
   function buy (uint32 id, uint64 priceForPurchase) external;
   function getPurchase () external returns (Purchase [] purchaseArray);
}
