
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

   struct Purchase {
       uint32 id;
       string name;
       uint32 number;
       uint64 createdAt;
       bool isBought;
       uint64 priceForPurchase;
   }

    struct SummaryOfShopping {
        uint32 paidCount;
        uint32 unpaidCount;
        uint64 sum;
    }

